[master]
    dns_alt_names = puppet,puppet-server
    autosign = /etc/puppetlabs/puppet/autosign.conf

[agent]
    server = puppet
    certname = windows-agent
[server]
storeconfigs_backend = puppetdb
storeconfigs = true
reports = puppetdb
